version: '3.7'
services:
  app:
    image: bus-system
    container_name: bus-system-app
    restart: unless-stopped
    build:
      args:
        user: www-user
        uid: 1000
      context: ./
      dockerfile: ./deploy/Dockerfile
    env_file: .env
    volumes:
      - ./:/home/web/www
      - uploads:/home/web/www/public/media
    links:
      - db

  db:
    image: "mysql:5.7"
    container_name: bus-system-db
    restart: unless-stopped
    ports:
      - 3307:3306
    volumes:
      - dbdata:/var/lib/mysql
      - dbsocket:/var/run/mysqld
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}

  nginx:
    container_name: bus-system-nginx
    build:
      context: ./
      dockerfile: deploy/web.dockerfile
    volumes:
      - ./public:/home/web/www/public/
      - uploads:/home/web/www/public/media
      - ./deploy/nginx/bus.nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    links:
      - app

volumes:
  dbdata:
  dbsocket:
  uploads:
